services:
  query-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: query-frontend
    ports:
      - "80:80"
    networks:
      - query-shared
    restart: unless-stopped

networks:
  query-shared:
    external: true
    name: query-shared
