server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    client_max_body_size 500M;

    location /query-frontend/ {
        try_files $uri $uri/ /query-frontend/index.html;
    }

    location = / {
        return 302 /query-frontend/;
    }

    location = /ping {
        proxy_pass http://cloud_webserver_v2:8080/ping;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /api/v2 {
        proxy_pass http://cloud_webserver_v2:8080;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 30s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
    }

    location /api/v2/ {
        proxy_pass http://cloud_webserver_v2:8080;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 30s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
    }
}
